# Generated by Django 5.2 on 2025-04-13 23:12

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='audios/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postAudioPost', to='blog.basepost')),
            ],
        ),
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postFilePost', to='blog.basepost')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImagePost', to='blog.basepost')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postVideoPost', to='blog.basepost')),
            ],
        ),
    ]
