# Generated by Django 5.2 on 2025-05-25 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewport', models.JSONField(default=dict, help_text='Viewport position and zoom')),
                ('flow_settings', models.JSONField(default=dict, help_text='React Flow settings and configurations')),
                ('is_public', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=100)),
                ('edge_type', models.CharField(choices=[('default', 'Default'), ('straight', 'Straight'), ('step', 'Step'), ('smoothstep', 'Smooth Step'), ('bezier', 'Bezier'), ('custom', 'Custom')], default='default', max_length=50)),
                ('source_node_id', models.CharField(max_length=100)),
                ('target_node_id', models.CharField(max_length=100)),
                ('source_handle', models.CharField(blank=True, max_length=100)),
                ('target_handle', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('label_style', models.JSONField(blank=True, default=dict)),
                ('animated', models.BooleanField(default=False)),
                ('deletable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flow.flowchart')),
            ],
            options={
                'unique_together': {('flow_chart', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='FlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flow_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flow.flowchart')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('flow_chart', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('default', 'Default'), ('input', 'Input'), ('output', 'Output'), ('custom', 'Custom')], default='default', max_length=50)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('data', models.JSONField(default=dict)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('draggable', models.BooleanField(default=True)),
                ('selectable', models.BooleanField(default=True)),
                ('deletable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.flowchart')),
            ],
            options={
                'unique_together': {('flow_chart', 'node_id')},
            },
        ),
    ]
